# Generated by Django 4.2.28 on 2026-06-21 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_patientvisit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='wardadmission',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.ward'),
        ),
    ]
