# Generated by Django 4.2.28 on 2026-03-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('records', '0006_surgery_status_pending_underway_ended'),
]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='surgery_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='surgery',
            name='surgery_drug_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='surgery',
            name='surgery_fee_parts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='surgery',
            name='surgery_lab_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wardadmission',
            name='admission_fee_parts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='visit_summary',
            field=models.TextField(blank=True),
        ),
    ]
