# Generated by Django 4.2.28 on 2026-03-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_new_fields'),
        ('records', '0007_surgery_surgery_discount_amount_and_more'),
    ]

    operations = [
    ]
