# Generated by Django 4.2.28 on 2026-03-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_merge_20260303_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisit',
            name='visit_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft — Awaiting Patient Review'), ('patient_reviewed', 'Patient Reviewed — Awaiting Payment'), ('pending', 'Pending — Awaiting Surgery'), ('underway', 'Underway'), ('ended', 'Ended'), ('paid', 'Paid — Scheduled'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
