# Generated by Django 4.2.28 on 2026-03-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_remove_payment_surgery_payment_alter_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='surgery_payment',
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='part_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_group',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('lab', 'Lab Tests'), ('prescription', 'Prescription / Drugs'), ('admission', 'Ward Admission'), ('surgery', 'Surgery'), ('admission_medication', 'Ward Medication')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_parts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
